<a href="https://colab.research.google.com/github/tuli-pen/Python_de_0_a_NLP/blob/master/Leccion_03_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Curso Python "De 0 a NLP"**

*Tuli Peña Melo, enero de 2024*
# Lección 03 | Pandas

In [ ]:
# Abreviatura usual para Pandas
import pandas as pd

## Estructuras de datos en Pandas

Pandas ofrece dos estructuras de datos principales: `Series` y `DataFrame`.

### Series

Una Serie es una estructura unidimensional que puede contener cualquier tipo de datos.

Es como una columna en una hoja de cálculo.

**s = pd.Series(datos,** index=índice)
* **datos** puede ser una lista, un diccionario, un único elemento o un array de numpy
* **índice** es una lista que se usará para etiquetar el índice de cada dato. Pueden haber índices duplicados.

**Usando listas**

In [ ]:
# Crear una Serie
serie = pd.Series([10, 20, 30, 40])
print(serie)

0    10
1    20
2    30
3    40
dtype: int64

In [ ]:
# Crear una Serie con un índice personalizado
serie = pd.Series([10, 20, 30, 40], index=range(8, 12))
print(serie)

8     10
9     20
10    30
11    40
dtype: int64

In [ ]:
# Crear una Serie con otros índices personalizados
serie = pd.Series([10, ['abcdef', 'g'], ('si', 'no'), 'Holaaa', 'Holaaa'], index=[[1,2], (3,4), 'Holaaa', 82, 'Holaaa'])
print(serie)

[1, 2]             10
(3, 4)    [abcdef, g]
Holaaa       (si, no)
82             Holaaa
Holaaa         Holaaa
dtype: object

**Usando diccionarios**

In [ ]:
# Usará las claves como índices
# Creará la serie en el orden que esté en el diccionario
dicc = {"b": 1, "a": 0, "c": 2}
mi_serie = pd.Series(dicc)
print(mi_serie)

b    1
a    0
c    2
dtype: int64

In [ ]:
# Si le pasamos un diccionario y unos índices aparte buscará esos índices en el diccionario
# (NaN signfica Not a Number y es como Pandas marca un dato faltante)

dicc = {"a": 0.0, "b": 1.0, "c": 2.0}
serie = pd.Series(dicc)
print(serie, '\n')

serie_2 = pd.Series(dicc, index=["b", "c", "d", "a"])
print(serie_2)

a    0.0
b    1.0
c    2.0
dtype: float64

b    1.0
c    2.0
d    NaN
a    0.0
dtype: float64

**Usando un único elemento**

In [ ]:
a = pd.Series(5.934853)
print(a)

0    5.934853
dtype: float64

In [ ]:
# Cuando usamos un elemento, pero le pasamos índices, crea una fila para cada índice
a = pd.Series('Hola', index=["a", "b", "c", "d", "e"])
print(a)

a    Hola
b    Hola
c    Hola
d    Hola
e    Hola
dtype: object

**Usando un array de numpy**

In [ ]:
import numpy as np
rng = np.random.default_rng()
nums_random = rng.integers(10, 21, 5)
print(nums_random, '\n')

serie = pd.Series(nums_random, index=["a", "b", "c", "d", "e"])
print(serie)

[13 20 17 10 13]

a    13
b    20
c    17
d    10
e    13
dtype: int64

Toda Serie tiene un nombre.

Para cambiarle el nombre usamos esta sintaxis:

s = pd.Series(datos, index=índice, **name='nombre'**)

In [ ]:
s = pd.Series('Elemento', index=[10,11,12], name="Ernesto Pérez")
print(s)

10    Elemento
11    Elemento
12    Elemento
Name: Ernesto Pérez, dtype: object

### DataFrame

Un DataFrame es una estructura bidimensional.

Su funcionamiento es como una **hoja de cálculo** y su estructura es como **un diccionario de Series.**

Esta es su sintaxis:

**df = pd.DataFrame(datos,** index= índices filas, columns= índices columnas )
* **datos** puede ser un array de numpy de 2 dimensiones, un diccionario, listas, series u otro DataFrame
* Se suele llamar df por convención

**Usando un array de numpy**

In [ ]:
import numpy as np
mi_array = np.array([[200,300,400], [500,600,700]])
mi_df = pd.DataFrame(mi_array)

# Nota: colab puede imprimir los DataFrames de una forma especial
print(mi_df)

     0    1    2
0  200  300  400
1  500  600  700

In [ ]:
mi_array = np.array([[200,300,400], [500,600,700]])
mi_df = pd.DataFrame(mi_array, index=['uno', 'dos'], columns=[5,6,7])
mi_df

**Usando un diccionario**

In [ ]:
# Crear un DataFrame a partir de un diccionario de listas
# Tomará las claves como columnas
data = {'Nombre': ['Laura', 'Ana', 'María', 'Rosa'],
        'Edad': [25, 30, 35, 40],
        'Ciudad': ['Medellín', 'Bogotá', 'Barranquilla', 'Bucaramanga']}

df = pd.DataFrame(data)
df

  Nombre  Edad        Ciudad
0  Laura    25      Medellín
1    Ana    30        Bogotá
2  María    35  Barranquilla
3   Rosa    40   Bucaramanga

In [ ]:
# Crear un DataFrame a partir de un diccionario de series
# Tomará las claves como columnas
d = {"one": pd.Series([1.0, 2.0, 3.0], index=["a", "b", "c"]),
    "two": pd.Series([1.0, 2.0, 3.0, 4.0], index=["a", "b", "c", "d"])}
print(d, '\n')

df = pd.DataFrame(d)
df

{'one': a    1.0
b    2.0
c    3.0
dtype: float64, 'two': a    1.0
b    2.0
c    3.0
d    4.0
dtype: float64}

   one  two
a  1.0  1.0
b  2.0  2.0
c  3.0  3.0
d  NaN  4.0

In [ ]:
# ¿Qué pasa si al crear el DataFrame anterior le pasamos índices o columnas?

In [ ]:
# Índices
df = pd.DataFrame(d, index=['d', 'a'])
df

In [ ]:
# Columnas
df = pd.DataFrame(d, columns=['primera', 'segunda'])
df

In [ ]:
# Crear un DataFrame a partir de un diccionario de arrays de numpy de 1 dimensión
# Tomará las claves como columnas
dicc_arrays = {"columna 1": [1.0, 2.0, 3.0, 4.0], "columna dos": [4.0, 3.0, 2.0, 1.0]}

pd.DataFrame(dicc_arrays)

   columna 1  columna dos
0        1.0          4.0
1        2.0          3.0
2        3.0          2.0
3        4.0          1.0

In [ ]:
# El diccionario anterior era de arrays, no de Series,
# por lo tanto esos arrays no tenían índices

# ¿Qué pasa si al crear el DataFrame anterior le pasamos índices o columnas?

In [ ]:
# Índices
df = pd.DataFrame(dicc_arrays, index=['a', 'b', 'c', 'd'])
df

In [ ]:
# Columnas
df = pd.DataFrame(dicc_arrays, columns=['primera', 'segunda'])
df

**Usando listas**

In [ ]:
# Usando una lista de diccionarios
data2 = [{"a": 1, "b": 2}, {"a": 5, "b": 10, "c": 20.6}]

In [ ]:
pd.DataFrame(data2)

   a   b     c
0  1   2   NaN
1  5  10  20.6

In [ ]:
pd.DataFrame(data2, index=['dicc1', 'dicc2'])

       a   b     c
dicc1  1   2   NaN
dicc2  5  10  20.6

**Usando Series**

In [ ]:
ser = pd.Series(range(5), index=list("abc e"), name="Ernesto Pérez")

pd.DataFrame(ser)

   Ernesto Pérez
a              0
b              1
c              2
               3
e              4

## —— Mini Test ——

In [ ]:
# Diccionario
datos = {
    'Nombre': ['Juan', 'María', 'Pedro', 'Ana'],
    'Edad': [25, 30, 22, 28],
    'Ciudad': ['México', 'Madrid', 'Buenos Aires', 'Lima']
}

# Crea un DataFrame con el diccionario dado y con unos índices que digan "Persona 1", "Persona 2" y así sucesivamente
# Imprime el DataFrame

# Tu código aquí:

In [ ]:
# Lista de diccionarios
datos2 = [
    {'Nombre': 'Pepito', 'Edad': 25, 'Ciudad': 'Madrid'},
    {'Nombre': 'Lucía', 'Edad': 30, 'Ciudad': 'Barcelona'},
    {'Nombre': 'Cecilia', 'Edad': 22, 'Ciudad': 'Valencia'},
    {'Nombre': 'Pablo', 'Edad': 28, 'Ciudad': 'Sevilla'}
]

# Crea un DataFrame con la lista de diccionarios dada, pero sólo con las columnas Edad y Nombre
# Luego imprimer el DataFrame, la primera columna debe ser edad y la segunda Nombre

# Tu código aquí:

## Operaciones básicas en Pandas

A continuación, veremos algunas operaciones básicas que se pueden realizar en Pandas.

In [ ]:
# Crear un DataFrame de ejemplo
data = {'Nombre': ['Amara', 'Bruno', 'Carlos', 'David', 'Ernesto', 'Fernanda'],
        'Edad': [25, 30, 35, 40, 21, 15],
        'Puntuación': [90, 85, 88, 92, 70, 94]}

df = pd.DataFrame(data)
df

     Nombre  Edad  Puntuación
0     Amara    25          90
1     Bruno    30          85
2    Carlos    35          88
3     David    40          92
4   Ernesto    21          70
5  Fernanda    15          94

### Acceder por índices

Si tu DataFrame se llama df:

**df.iloc[filas, columnas]**

In [ ]:
# Acceder a la primera fila
fila_0 = df.iloc[0]

# Acceder a la segunda columna
columna_1 = df.iloc[:, 1]

# Acceder a una celda específica (por ejemplo, la celda en la tercera fila y segunda columna)
celda = df.iloc[2, 1]

# Acceder a un subconjunto del DataFrame (por ejemplo, las primeras dos filas y las primeras dos columnas)
subconjunto = df.iloc[:2, :2]

# Mostrar los resultados
print("Primera fila:\n", fila_0, '\n')
print("\nSegunda columna:\n", columna_1, '\n')
print("\nCelda específica:\n", celda, '\n')
print("\nSubconjunto:\n", subconjunto)

Primera fila:
 Nombre        Amara
Edad             25
Puntuación       90
Name: 0, dtype: object


Segunda columna:
 0    25
1    30
2    35
3    40
4    21
5    15
Name: Edad, dtype: int64


Celda específica:
 35


Subconjunto:
   Nombre  Edad
0  Amara    25
1  Bruno    30

### Visualización de los primeros datos

Si tu DataFrame se llama df:

**df.head(número de datos que quieres ver)**

In [ ]:
# Visualizar las primeras 2 filas de un DataFrame
df.head(2)

  Nombre  Edad  Puntuación
0  Amara    25          90
1  Bruno    30          85

In [ ]:
# Por defecto df.head() muestra las 5 primeras filas del DataFrame
df.head()

    Nombre  Edad  Puntuación
0    Amara    25          90
1    Bruno    30          85
2   Carlos    35          88
3    David    40          92
4  Ernesto    21          70

### Columnas

**Visualizar una columna**

In [ ]:
# La sintaxis es la misma que si "df" fuera un diccionario y
# quisieramos imprimir el valor asociado a la clave "Nombre"

df['Nombre']

0       Amara
1       Bruno
2      Carlos
3       David
4     Ernesto
5    Fernanda
Name: Nombre, dtype: object

In [ ]:
# Podemos hacer splice

df['Nombre'][:3]

0     Amara
1     Bruno
2    Carlos
Name: Nombre, dtype: object

**Agregar una columna**

In [ ]:
# También es como si df fuera un diccionario
df['Estado civil'] = ['Soltera', 'Casado', 'Viudo', 'Casado', 'Soltero', 'Soltera']
df

     Nombre  Edad  Puntuación Estado civil
0     Amara    25          90      Soltera
1     Bruno    30          85       Casado
2    Carlos    35          88        Viudo
3     David    40          92       Casado
4   Ernesto    21          70      Soltero
5  Fernanda    15          94      Soltera

In [ ]:
# Podemos hacer operaciones entre columnas
df['#'] = df['Edad'] + df['Puntuación']
df

     Nombre  Edad  Puntuación Estado civil    #
0     Amara    25          90      Soltera  115
1     Bruno    30          85       Casado  115
2    Carlos    35          88        Viudo  123
3     David    40          92       Casado  132
4   Ernesto    21          70      Soltero   91
5  Fernanda    15          94      Soltera  109

In [ ]:
# Si son strings el símbolo + las concatena
df['#'] = df['Nombre'] + df['Estado civil']
df

     Nombre  Edad  Puntuación Estado civil                #
0     Amara    25          90      Soltera     AmaraSoltera
1     Bruno    30          85       Casado      BrunoCasado
2    Carlos    35          88        Viudo      CarlosViudo
3     David    40          92       Casado      DavidCasado
4   Ernesto    21          70      Soltero   ErnestoSoltero
5  Fernanda    15          94      Soltera  FernandaSoltera

In [ ]:
# También podemos hacer operaciones que devuelven booleanos
df['Aprobaron'] = df['Puntuación'] > 86
df

     Nombre  Edad  Puntuación Estado civil                #  Aprobaron
0     Amara    25          90      Soltera     AmaraSoltera       True
1     Bruno    30          85       Casado      BrunoCasado      False
2    Carlos    35          88        Viudo      CarlosViudo       True
3     David    40          92       Casado      DavidCasado       True
4   Ernesto    21          70      Soltero   ErnestoSoltero      False
5  Fernanda    15          94      Soltera  FernandaSoltera       True

In [ ]:
# Si le pasamos un solo valor lo pondrá en todas las filas
df["NuevaColumna"] = "Holaaaa"
df

,Nombre,Edad,Puntuación,Estado civil,#,Aprobaron,NuevaColumna
0,Amara,25,90,Soltera,AmaraSoltera,True,Holaaaa
1,Bruno,30,85,Casado,BrunoCasado,False,Holaaaa
2,Carlos,35,88,Viudo,CarlosViudo,True,Holaaaa
3,David,40,92,Casado,DavidCasado,True,Holaaaa
4,Ernesto,21,70,Soltero,ErnestoSoltero,False,Holaaaa
5,Fernanda,15,94,Soltera,FernandaSoltera,True,Holaaaa

**Borrar una columna**

In [ ]:
# También es como si fuera un diccionario
del df['#']
del df['NuevaColumna']
df

     Nombre  Edad  Puntuación Estado civil  Aprobaron
0     Amara    25          90      Soltera       True
1     Bruno    30          85       Casado      False
2    Carlos    35          88        Viudo       True
3     David    40          92       Casado       True
4   Ernesto    21          70      Soltero      False
5  Fernanda    15          94      Soltera       True

### Filtrado de datos

Si tu DataFrame se llama df:

**df.loc[filtro que quieres aplicar]**
* Un filtro nos permitirá mostrar solo algunas filas del DataFrame
* Un filtro es una condición que se declara sobre alguna de las columnas

In [ ]:
# Filtrar por edad mayor a 30
df.loc[df['Edad'] > 30]

   Nombre  Edad  Puntuación Estado civil  Aprobaron
2  Carlos    35          88        Viudo       True
3   David    40          92       Casado       True

In [ ]:
# Filtrar por estado civil igual a 'Soltera'
df.loc[df['Estado civil'] == 'Soltera']

     Nombre  Edad  Puntuación Estado civil  Aprobaron
0     Amara    25          90      Soltera       True
5  Fernanda    15          94      Soltera       True

In [ ]:
# Filtrar por aquellos que aprobaron
df.loc[df['Aprobaron'] == True]

     Nombre  Edad  Puntuación Estado civil  Aprobaron
0     Amara    25          90      Soltera       True
2    Carlos    35          88        Viudo       True
3     David    40          92       Casado       True
5  Fernanda    15          94      Soltera       True

In [ ]:
# Filtrar por aquellos que son solteros y tienen una puntuación menor a 80
df.loc[(df['Estado civil'] == 'Soltero') & (df['Puntuación'] < 80)]

    Nombre  Edad  Puntuación Estado civil  Aprobaron
4  Ernesto    21          70      Soltero      False

### Operaciones sobre los valores de una columna

In [ ]:
# Contar la cantidad de filas que tienen la misma puntuación
df['Puntuación'].value_counts()

90    1
85    1
88    1
92    1
70    1
94    1
Name: Puntuación, dtype: int64

In [ ]:
# Calcular la media de las edades
df['Edad'].mean()

27.666666666666668

In [ ]:
# Traer la edad mínima
df['Edad'].min()

15

In [ ]:
# .describe() genera un resumen estadístico que incluye la media, desviación estándar, mínimo, máximo y cuartiles
df['Edad'].describe()

count     6.000000
mean     27.666667
std       9.201449
min      15.000000
25%      22.000000
50%      27.500000
75%      33.750000
max      40.000000
Name: Edad, dtype: float64

In [ ]:
# Le suma 5 a todas las edades
df['Edad'].add(5)

0    30
1    35
2    40
3    45
4    26
5    20
Name: Edad, dtype: int64

In [ ]:
# Notemos que la operación anterior no afectó el dataframe original
df['Edad']

0    25
1    30
2    35
3    40
4    21
5    15
Name: Edad, dtype: int64

In [ ]:
# Le sumamos las edades al puntaje
df['Puntuación'].add(df['Edad'])

0    115
1    115
2    123
3    132
4     91
5    109
dtype: int64

In [ ]:
# Convertimos la columna Nombre en una lista
df['Nombre'].tolist()

['Amara', 'Bruno', 'Carlos', 'David', 'Ernesto', 'Fernanda']

## Filas

**Agregar una nueva fila**

Debemos crear un DataFrame de una sola fila y luego concatenarlo con el DataFrame original.

In [ ]:
# Escribimos una fila nueva
persona_nueva = {'Nombre': 'Germán', 'Edad': 36, 'Puntuación': 87, 'Aprobaron':True}
persona_nueva_df = pd.DataFrame(persona_nueva, index=[0])
persona_nueva_df

   Nombre  Edad  Puntuación  Aprobaron
0  Germán    36          87       True

In [ ]:
# Pegamos la fila nueva al DataFrame de bebidas
# Ponemos ignore_index=True para que resetee los índices después de pegarlos
df_2 = pd.concat([df, persona_nueva_df], ignore_index=True)
df_2

     Nombre  Edad  Puntuación Estado civil  Aprobaron
0     Amara    25          90      Soltera       True
1     Bruno    30          85       Casado      False
2    Carlos    35          88        Viudo       True
3     David    40          92       Casado       True
4   Ernesto    21          70      Soltero      False
5  Fernanda    15          94      Soltera       True
6    Germán    36          87          NaN       True

In [ ]:
# ¿Qué pasa si no ponemos ignore_index=True?
df_3 = pd.concat([df, persona_nueva_df])
df_3

     Nombre  Edad  Puntuación Estado civil  Aprobaron
0     Amara    25          90      Soltera       True
1     Bruno    30          85       Casado      False
2    Carlos    35          88        Viudo       True
3     David    40          92       Casado       True
4   Ernesto    21          70      Soltero      False
5  Fernanda    15          94      Soltera       True
0    Germán    36          87          NaN       True

In [ ]:
# Reseteemos los índices de df_3
df_3 = df_3.reset_index()
df_3

   index    Nombre  Edad  Puntuación Estado civil  Aprobaron
0      0     Amara    25          90      Soltera       True
1      1     Bruno    30          85       Casado      False
2      2    Carlos    35          88        Viudo       True
3      3     David    40          92       Casado       True
4      4   Ernesto    21          70      Soltero      False
5      5  Fernanda    15          94      Soltera       True
6      0    Germán    36          87          NaN       True

In [ ]:
# Ahora borremos la fila de indices vieja
del df_3['index']
df_3

     Nombre  Edad  Puntuación Estado civil  Aprobaron
0     Amara    25          90      Soltera       True
1     Bruno    30          85       Casado      False
2    Carlos    35          88        Viudo       True
3     David    40          92       Casado       True
4   Ernesto    21          70      Soltero      False
5  Fernanda    15          94      Soltera       True
6    Germán    36          87          NaN       True

## Transponer

Si tu DataFrame se llama df:

**df.T**

In [ ]:
df = df.T
df

                    0       1       2       3        4         5       6
Nombre          Amara   Bruno  Carlos   David  Ernesto  Fernanda  Germán
Edad               25      30      35      40       21        15      36
Puntuación         90      85      88      92       70        94      87
Estado civil  Soltera  Casado   Viudo  Casado  Soltero   Soltera     NaN
Aprobaron        True   False    True    True    False      True    True

## —— Mini Test ——

In [ ]:
# DataFrame de libros
data1 = {
    'Título': ['El señor de los anillos', 'Cien años de soledad', '1984', 'Orgullo y prejuicio'],
    'Autor': ['J.R.R. Tolkien', 'Gabriel García Márquez', 'George Orwell', 'Jane Austen'],
    'Año de publicación': [1954, 1967, 1949, 1813],
    'Género': ['Fantasía', 'Realismo mágico', 'Distopía', 'Romance']
}
df_libros = pd.DataFrame(data1)
df_libros

,Título,Autor,Año de publicación,Género
0,El señor de los anillos,J.R.R. Tolkien,1954,Fantasía
1,Cien años de soledad,Gabriel García Márquez,1967,Realismo mágico
2,1984,George Orwell,1949,Distopía
3,Orgullo y prejuicio,Jane Austen,1813,Romance

In [ ]:
# Usando los índices del DataFrame:
# - Imprime solo la columna de los títulos
# - Imprime solo la fila de Orgullo y prejuicio
# - Imprime solo la palabra "Romance"

# Tu código aquí:

In [ ]:
# DataFrame de mascotas
data2 = {
    'Nombre': ['Max', 'Bella', 'Charlie', 'Luna', 'Rocky'],
    'Edad': [3, 2, 5, 1, 4],
    'Tipo': ['Perro', 'Gato', 'Perro', 'Gato', 'Iguana'],
    'Color': ['Marrón', 'Gris', 'Negro', 'Blanco', 'Verde']
}
df_mascotas = pd.DataFrame(data2)
df_mascotas

    Nombre  Edad    Tipo   Color
0      Max     3   Perro  Marrón
1    Bella     2    Gato    Gris
2  Charlie     5   Perro   Negro
3     Luna     1    Gato  Blanco
4    Rocky     4  Iguana   Verde

In [ ]:
# Borra la columna Edad del DataFrame anterior e imprime el DataFrame de nuevo

# Tu código aquí:

In [ ]:
# DataFrame de estudiantes
data3 = {'Nombre': ['Juan', 'Ana', 'Pedro', 'María', 'Luis'],
        'Edad': [26, 22, 21, 23, 19],
        'Género': ['M', 'F', 'M', 'F', 'M'],
        'Promedio': [85, 92, 78, 95, 89]}
df_estudiantes = pd.DataFrame(data3)
df_estudiantes

  Nombre  Edad Género  Promedio
0   Juan    26      M        85
1    Ana    22      F        92
2  Pedro    21      M        78
3  María    23      F        95
4   Luis    19      M        89

In [ ]:
# A continuación filtra los estudiantes mayores de 20 años y con un promedio superior a 80
# Imprime el DataFrame con ese filtro

# Tu código aquí:

## De DataFrame a Array

Ya vimos como crear un **DataFrame** de Pandas a partir de un **Array** de Numpy.

Ahora veamos como pasar un **DataFrame** de Pandas a un **Array** de Numpy

In [ ]:
un_df = pd.DataFrame({'una':range(5,11), 'dos':range(10,16)})
un_df

   una  dos
0    5   10
1    6   11
2    7   12
3    8   13
4    9   14
5   10   15

In [ ]:
un_array = np.asarray(un_df)
print(un_array)

[[ 5 10]
 [ 6 11]
 [ 7 12]
 [ 8 13]
 [ 9 14]
 [10 15]]

## Pandas con archivos de Excel

### Abrir un archivo

**df = pd.read_excel('archivo_excel.xlsx',** index_col='nombre columna')

* Esto leerá el archivo de Excel como un DataFrame y guardará el DataFrame en la variable df.
* A **index_col** le  pasamos el nombre de la columna que queremos que use como índices. Si no le pasamos index_col entonces Pandas creará índices predeterminados.

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
# Leemos un archivo de Excel
df_bebidas = pd.read_excel('/content/drive/MyDrive/_Tutorías NLP/Notebooks/bebidas.xlsx')
df_bebidas

          Bebida  Precio
0          Tinto    2500
1             Té    3000
2  Café en leche    5500
3       Malteada    9000
4      Chocolate    3000

In [ ]:
# Imprimimos las 2 primeras filas del DataFrame
df_bebidas.head(2)

  Bebida  Precio
0  Tinto    2500
1     Té    3000

In [ ]:
# Contamos cuantas bebidas tienen el mismo precio
df_bebidas['Precio'].value_counts()

3000    2
2500    1
5500    1
9000    1
Name: Precio, dtype: int64

In [ ]:
# Hacemos una lista con los nombres de las bebidas
df_bebidas['Bebida'].tolist()

['Tinto', 'Té', 'Café en leche', 'Malteada', 'Chocolate']

In [ ]:
# Imprimimos las bebidas que valgan más de 5000
df_bebidas.loc[df_bebidas['Precio'] > 5000]

          Bebida  Precio
2  Café en leche    5500
3       Malteada    9000

In [ ]:
# Agregamos una columna
df_bebidas['Tiempo preparación'] = ['5 minutos', '7 minutos', '7 minutos', '12 minutos', '8 minutos']
df_bebidas

          Bebida  Precio Tiempo preparación
0          Tinto    2500          5 minutos
1             Té    3000          7 minutos
2  Café en leche    5500          7 minutos
3       Malteada    9000         12 minutos
4      Chocolate    3000          8 minutos

In [ ]:
# Escribimos una fila nueva
bebida_nueva = {'Bebida': 'Gaseosa', 'Precio': 2000, 'Tiempo preparación': '1 minuto'}
bebida_nueva_df = pd.DataFrame(bebida_nueva, index=[0])
bebida_nueva_df

    Bebida  Precio Tiempo preparación
0  Gaseosa    2000           1 minuto

In [ ]:
# Pegamos la fila nueva al DataFrame de bebidas
df_bebidas = pd.concat([df_bebidas, bebida_nueva_df], ignore_index=True)
df_bebidas

          Bebida  Precio Tiempo preparación
0          Tinto    2500          5 minutos
1             Té    3000          7 minutos
2  Café en leche    5500          7 minutos
3       Malteada    9000         12 minutos
4      Chocolate    3000          8 minutos
5        Gaseosa    2000           1 minuto

### Guardar un archivo

**df.to_excel('nuevo_archivo_excel.xlsx',** index=False)

Si ponemos index=False no se guardará una primera columna con los índices.

In [ ]:
# Guardamos nuestro DataFrame editado en un nuevo archivo de Excel
df_bebidas.to_excel('/content/drive/MyDrive/_Tutorías NLP/Notebooks/nuevas_bebidas.xlsx', index=False)

In [ ]:
# Traemos ese archivo y lo imprimimos
nuevas_bebidas = pd.read_excel('/content/drive/MyDrive/_Tutorías NLP/Notebooks/nuevas_bebidas.xlsx')
nuevas_bebidas

          Bebida  Precio Tiempo preparación
0          Tinto    2500          5 minutos
1             Té    3000          7 minutos
2  Café en leche    5500          7 minutos
3       Malteada    9000         12 minutos
4      Chocolate    3000          8 minutos